"""Replay a recorded video as a FrameSource.

This is deliberately built in M0 rather than deferred. It is what lets a
detector change in M4 be re-run against every night recorded since M0, and the
resulting corpus is the most valuable asset the project will accumulate
(design.md §21). Building the seam later means rebuilding the corpus later,
which is impossible — those nights are gone.

Note that M0 never *writes* video (design.md §20). Replay sources come from
short consented calibration clips and from synthetic fixtures generated by the
test suite, not from overnight recordings.
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import Any, Optional

import cv2

from ..types import Frame
from .source import FrameSource, FrameSourceError


class FileReplaySource(FrameSource):
    """Frames from a video file.

    `realtime=False` (the default) runs as fast as the CPU allows and
    synthesises timestamps from the file's frame rate, which is what regression
    replay wants. `realtime=True` paces playback to wall-clock and is only for
    eyeballing a night back at natural speed.
    """

    def __init__(
        self,
        path: Path | str,
        *,
        realtime: bool = False,
        fps_override: Optional[float] = None,
        loop: bool = False,
    ) -> None:
        self._path = Path(path)
        self._realtime = realtime
        self._fps_override = fps_override
        self._loop = loop
        self._cap: Optional[cv2.VideoCapture] = None
        self._seq = 0
        self._exhausted = False
        self._fps = 30.0
        self._t0_mono = 0.0
        self._t0_utc = 0.0

    def open(self) -> None:
        if not self._path.exists():
            raise FrameSourceError(f"replay file not found: {self._path}")
        cap = cv2.VideoCapture(str(self._path))
        if not cap.isOpened():
            raise FrameSourceError(f"could not open replay file: {self._path}")
        self._cap = cap
        fps = self._fps_override or cap.get(cv2.CAP_PROP_FPS)
        # A malformed container can report 0 or a nonsense rate; fall back
        # rather than divide by zero when synthesising timestamps.
        self._fps = float(fps) if fps and fps > 1e-3 else 30.0
        self._t0_mono = time.monotonic()
        self._t0_utc = time.time()
        self._exhausted = False
        self._seq = 0

    def read(self) -> Optional[Frame]:
        if self._cap is None:
            raise FrameSourceError("read() before open()")
        ok, image = self._cap.read()
        if not ok or image is None:
            if self._loop:
                self._cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
                ok, image = self._cap.read()
            if not ok or image is None:
                self._exhausted = True
                return None

        offset = self._seq / self._fps
        self._seq += 1

        if self._realtime:
            target = self._t0_mono + offset
            delay = target - time.monotonic()
            if delay > 0:
                time.sleep(delay)

        return Frame(
            seq=self._seq,
            t_mono=self._t0_mono + offset,
            t_utc=self._t0_utc + offset,
            image=image,
        )

    def close(self) -> None:
        if self._cap is not None:
            self._cap.release()
            self._cap = None

    @property
    def exhausted(self) -> bool:
        return self._exhausted

    def device_profile(self) -> dict[str, Any]:
        cap = self._cap
        return {
            "camera_model": f"replay:{self._path.name}",
            "backend": "file",
            "width": int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) if cap else None,
            "height": int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) if cap else None,
            "fps": self._fps,
            "fourcc": None,
            "manual_exposure": None,
            "ir_wavelength_nm": None,
            "mount_geometry": None,
            "audio_device": None,
        }
